version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: secure_password
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./todo-server
    environment:
      - DB_NAME=todo
      - MYSQL_CONFIG={"write":{"host":"mysql","username":"todo","password":"secure_password","port":3306},"read":[{"host":"mysql","username":"todo","password":"secure_password","port":3306}]}
      - JWT_ACCESS_TOKEN_SECRET=secret
      - JWT_REFRESH_TOKEN_SECRET=secret
    depends_on:
      - mysql
    command: sh -c "npm install && npm run migrate && npm start"
    ports:
      - "8080:8080"

volumes:
  mysql-data:
